version: '3.8'
services:
  frontend:
    build:
      context: "./frontend"
    ports:
      - "80:80"
  backend:
    build: 
      context: "./backend/"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - prvnipf-net
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/1pf
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=heslo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  database:
    image: postgres:16.2
    environment:
      POSTGRES_DB: 1pf
      POSTGRES_USER: user
      POSTGRES_PASSWORD: heslo
    restart: always
    networks:
      - prvnipf-net
    volumes:
      - ./database/Rates.sql:/docker-entrypoint-initdb.d/Rates.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -h localhost -U user -d 1pf" ]
      timeout: 5s
      interval: 10s
      retries: 10
networks:
  prvnipf-net: